# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_blk" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tank/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "tank/root/nix";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/81abd72a-2821-43b2-ac49-934775fb9aaf";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "tank/root/data/home";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "tank/root/data/varlib";
      fsType = "zfs";
    };

  fileSystems."/home/infinisil/media" =
    { device = "tank/root/media";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/397c2076-a3ba-4acd-893f-adc27b18434d"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
}
