# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sd_mod" "virtio_blk" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/11b0b201-d195-42df-89b5-5cc2da17bb67";
      fsType = "ext4";
    };

  fileSystems."/ipfs" =
    { device = "volume1/ipfs";
      fsType = "zfs";
    };

  fileSystems."/global" =
    { device = "volume1/global";
      fsType = "zfs";
    };

  fileSystems."/backup" =
    { device = "volume1/backup";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/swap"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
}
