# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "pool/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "pool/root/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "pool/root/data/home";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "pool/root/data/varlib";
      fsType = "zfs";
    };

  fileSystems."/root" =
    { device = "pool/root/data/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "boot";
      fsType = "zfs";
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
