# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, config, lib, pkgs, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tank/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "tank/root/nix";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0a9ada6a-52a5-4f0b-af0a-a77f14077014";
      fsType = "ext4";
    };

  fileSystems."/var/lib/music" =
    { device = "tank/backup/vario/tank2/root/data/music";
      fsType = "zfs";
      options = [ "nofail" "ro" ];
    };

  fileSystems."/var/lib/torrent" =
    { device = "tank/root/torrent";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a716a4a0-dcae-4283-8b06-d75cb3b3a248"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  nix.settings.max-jobs = lib.mkDefault 2;
}
