directory: /home/infinisil/Music/data
library: /home/infinisil/Music/beets.db
plugins: [smartplaylist, mpdupdate]

mpd:
    host: localhost
    port: 6600

mpdupdate:
    host: localhost
    port: 6600

smartplaylist:
    playlist_dir: /home/infinisil/Music/mpd/playlists
    playlists:
        - name: all.m3u
          query: ''
        - name: test.m3u
          query: 'artist:"Katherine Jenkins"'
