# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "pool/encroot/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "pool/encroot/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "pool/encroot/data/home";
      fsType = "zfs";
    };

  fileSystems."/root" =
    { device = "pool/encroot/data/home/root";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "pool/encroot/data/varlib";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "boot";
      fsType = "zfs";
    };

  #fileSystems."/home/infinisil/music" =
  #  { device = "pool/backup/vario/tank2/root/data/music";
  #    fsType = "zfs";
  #    options = [ "nofail" ];
  #  };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/9D48-BDB4";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8d817dfb-4eb5-4c88-ac99-b9a2965f6265"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
