# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_blk" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "main/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "main/root/nix";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/d5f30c4e-5f44-4998-9c8b-7e62fe2113ce";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "main/root/data/home";
      fsType = "zfs";
    };

  fileSystems."/root" =
    { device = "main/root/data/root";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "main/root/data/varlib";
      fsType = "zfs";
    };

  fileSystems."/home/infinisil/music" =
    { device = "main/root/data/music";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5a75abf7-1fd3-4ec8-81ea-a872a3848e4a"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
}
