# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sd_mod" "virtio_blk" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "main";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "main/nix";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "main/data/var";
      fsType = "zfs";
    };

  fileSystems."/var/lib/imp" =
    { device = "main/data/var/important";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2111f700-00ad-4801-a0d1-ba21b12302c1";
      fsType = "ext4";
    };

  fileSystems."/home/infinisil/Music" =
    { device = "main/data/music";
      fsType = "zfs";
    };

  fileSystems."/var/lib/ipfs" =
    { device = "main/data/ipfs";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b7632d83-3b93-456e-878d-b7ccfc206bcb"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
}
