# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_blk" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "main/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "main/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/webroot" =
    { device = "main/webroot";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "main/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/da8a84bd-51b5-4fe6-a493-9ed44623256f";
      fsType = "ext4";
    };

  fileSystems."/global" =
    { device = "main/global";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9c41fd4b-1324-4519-a5fd-4cd82784d62c"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
}
