# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "main/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6490-C4A6";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "main/root/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "main/root/data/home";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "main/root/data/varlib";
      fsType = "zfs";
    };

  #fileSystems."/home/infinisil/music" =
  #  { device = "tank/root/music";
  #    fsType = "zfs";
  #  };

  fileSystems."/betty" =
    { device = "main/betty";
      fsType = "zfs";
    };

  fileSystems."/home/infinisil/media" =
    { device = "main/root/data/media";
      fsType = "zfs";
    };

  #swapDevices =
  #  [ { device = "/dev/disk/by-uuid/2e6c36d3-d42c-4e4c-99a3-e67707c20562"; }
  #  ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
