#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

hosts=$(nix-instantiate --eval --strict --json \
	"$DIR/connectivity.nix" -A hosts \
	| jq '.[]' -r
)

echo "Determining preferred ips for hosts.." >&2

echo "{"

for host in $hosts; do
	if [[ $# -ne 0 ]] && ! [[ "$*" =~ "$host" ]]; then
		continue
	fi

	candidates=$(nix-instantiate --eval --strict --json \
		"$DIR/connectivity.nix" -A "preferred.$(hostname).$host" \
		| jq '.[]' -r
	)

	for c in $candidates; do
		if ping "$c" -w1 -c1 2>/dev/null >/dev/null; then
			echo "  \"$host\" = \"$c\";"
			echo "Connecting to $host via $c" >&2
			continue 2
		fi
	done

	echo -e "Error: Can't reach host $host, tried pinging $(echo $candidates | xargs)" >&2

done

echo "}"
