#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
defSha256=0000000000000000000000000000000000000000000000000000

shopt -s extglob

if [ -z "$@" ]; then
  attrs=$(nix-instantiate --eval --strict --json \
		-E "builtins.attrNames (import $DIR/default.nix)" \
		| jq '.[]' -r)
else
	attrs="$@"
fi

for attr in $attrs; do
	file=$(nix-instantiate --eval --strict --json \
		"$DIR/default.nix" -A "$attr.file" | jq . -r)

	oldRev=$(rg 'rev *= *"(.*)"' "$file" -or '$1')

	gitDir=$(nix-instantiate --eval --strict --json \
		"$DIR/default.nix" -A "$attr.meta.homepage" | jq . -r)

	branch=$(nix-instantiate --eval --strict --json \
		-E "(import $DIR/default.nix).$attr.meta.branch or \"\"" | jq . -r)

	masterRev=$(git ls-remote "$gitDir" "${branch:-HEAD}" | cut -f1)

	if [ "$oldRev" = "$masterRev" ]; then
		echo "$gitDir is up to date"
	else
		echo -n "$gitDir has been updated from $(echo "$oldRev" | cut -b1-8) to" \
			"$(echo "$masterRev" | cut -b1-8), updating $file..  "

		tmp=$(mktemp)
		sed "$file" >"$tmp" \
			-e "s/rev *= *\".*\"/rev = \"$masterRev\"/" \
			-e "s/sha256 *= *\".*\"/sha256 = \"$defSha256\"/"

		correctHash=$(nix-build "$DIR/call.nix" 2>&1 \
			--arg file "$tmp" --no-out-link \
			| rg "got:.*sha256:([a-z0-9]*)" -or '$1')

		sed -i "$file" \
			-e "s/rev *= *\".*\"/rev = \"$masterRev\"/" \
			-e "s/sha256 *= *\".*\"/sha256 = \"$correctHash\"/"

		echo "Done"
	fi
done

